In [ ]:
!pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
data = {
    "Tenure":[1,2,3,4,5,6,7,8,9,10,12,15,18,20,24],
    "MonthlyCharges":[90,85,80,78,75,70,65,60,55,50,45,40,35,30,25],
    "Contract":["Month-to-month","Month-to-month","Month-to-month","Month-to-month","One year",
                "One year","One year","One year","Two year","Two year",
                "Two year","Two year","Two year","Two year","Two year"],
    "Churn":["Yes","Yes","Yes","Yes","No",
             "No","No","No","No","No",
             "No","No","No","No","No"]
}

df = pd.DataFrame(data)

df.head()

   Tenure  MonthlyCharges        Contract Churn
0       1              90  Month-to-month   Yes
1       2              85  Month-to-month   Yes
2       3              80  Month-to-month   Yes
3       4              78  Month-to-month   Yes
4       5              75        One year    No

In [ ]:
le = LabelEncoder()

df["Contract"] = le.fit_transform(df["Contract"])
df["Churn"] = le.fit_transform(df["Churn"])

df.head()

   Tenure  MonthlyCharges  Contract  Churn
0       1              90         0      1
1       2              85         0      1
2       3              80         0      1
3       4              78         0      1
4       5              75         1      0

In [ ]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))

print("\nClassification Report:\n")
print(classification_report(y_test, predictions))

Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

In [ ]:
tenure = int(input("Enter Customer Tenure: "))
monthly = float(input("Enter Monthly Charges: "))
contract = int(input("Contract Type (0=Month,1=One Year,2=Two Year): "))

customer = [[tenure, monthly, contract]]

prediction = model.predict(customer)

if prediction[0] == 1:
    print("Customer will Leave (Churn)")
else:
    print("Customer will Stay")

Enter Customer Tenure: 2
Enter Monthly Charges: 85
Contract Type (0=Month,1=One Year,2=Two Year): 0
Customer will Leave (Churn)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
import pickle

pickle.dump(model, open("customer_churn_model.pkl", "wb"))

print("Model Saved Successfully")

Model Saved Successfully